MvcPractice/MvcPractice/Controllers/HighScoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcPractice.Controllers
{
    public class HighScoresController : Controller
    {
        //
        // GET: /HighScores/

        public ActionResult Index()
        {
            return View();
        }


        public ActionResult GuessThatNumber()
        {
            Models.Entities db = new Models.Entities();
            return View(db.HighScores.Where(x => x.Game == "GuessThatNumber"));
        }

        public ActionResult Battleship()
        {
            Models.Entities db = new Models.Entities();
            return View(db.HighScores.Where(x => x.Game == "Battleship"));
        }

        public ActionResult Hangman()
        {
            Models.Entities db = new Models.Entities();
            return View(db.HighScores.Where(x => x.Game == "Hangman"));
        }

        public ActionResult CombatSimulator()
        {
            Models.Entities db = new Models.Entities();
            return View(db.HighScores.Where(x => x.Game == "CombatSimulator"));
        }

        public ActionResult Trivia()
        {
            Models.Entities db = new Models.Entities();
            return View(db.HighScores.Where(x => x.Game == "Trivia"));
        }

    }
}

MvcPractice/MvcPractice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <h1>Matts Super Cool Website</h1>
     <a href="@Url.Action("Index", "Home")">
        Home
     </a>
    &nbsp; &nbsp;
    <a href="@Url.Action("About", "Home")">
        About
    </a>
    &nbsp; &nbsp;
    <a href="@Url.Action("Index", "HighScores")">
        High Scores
    </a>
    &nbsp; &nbsp;
    <a href="@Url.Action("Index", "Contact")">
        Contact Us
    </a>
     &nbsp; &nbsp;
    <a href="@Url.Action("Index", "Admin")">
        Admin
    </a>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>