Week6CodingChallenge/Week6CodingChallenge/Models/ContactForm.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week6CodingChallenge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactForm
    {
        public int ContactFormID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
    }
}

Week6CodingChallenge/Week6CodingChallenge/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week6CodingChallenge.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContactEntities : DbContext
    {
        public ContactEntities()
            : base("name=ContactEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ContactForm> ContactForms { get; set; }
    }
}

Week6CodingChallenge/Week6CodingChallenge/Models/Model1.Designer.cs
// Default code generation is disabled for model 'C:\Users\Technologist\Documents\GitHub\MattsWeek1Solutions\Week6CodingChallenge\Week6CodingChallenge\Models\Model1.edmx'. 
// To enable default code generation, change the value of the 'Code Generation Strategy' designer
// property to an alternate value. This property is available in the Properties Window when the model is
// open in the designer.

Week6CodingChallenge/Week6CodingChallenge/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Week6CodingChallenge/Week6CodingChallenge/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Week6CodingChallenge.Controllers
{
    public class AboutController : Controller
    {
        //
        // GET: /About/

        public ActionResult Index()
        {
            return PartialView();
        }

        public ActionResult Who()
        {
            return PartialView();
        }

        public ActionResult What()
        {
            return PartialView();
        }

        public ActionResult Why()
        {
            return PartialView();
        }

        public ActionResult How()
        {
            return PartialView();
        }

        public ActionResult Where()
        {
            return PartialView();
        }

    }
}

Week6CodingChallenge/Week6CodingChallenge/Controllers/CareersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Week6CodingChallenge.Controllers
{
    public class CareersController : Controller
    {
        //
        // GET: /Careers/

        public ActionResult Index()
        {
            return PartialView();
        }

    }
}

Week6CodingChallenge/Week6CodingChallenge/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Mail;

namespace Week6CodingChallenge.Controllers
{
    public class ContactController : Controller
    {
        //
        // GET: /Contact/
        [HttpGet]
        public ActionResult Index()
        {
            return PartialView(new Week6CodingChallenge.Models.ContactForm());
        }

        //[HttpPost]
        //public ActionResult Index(Models.ContactForm contactForm)
        //{
        //    //create a connection database
        //    Models.ContactForm db = new Models.ContactForm();
        //    //Add contact info to database
        //    db.ContactForm.Add(contactForm);
        //    //save changes
        //    db.SaveChanges();
        //    //Kick user to thank you page
        //    return RedirectToAction("Index", "Home");
        //}

        //new contact form post

        [HttpPost]
        public ActionResult Index(Week6CodingChallenge.Models.ContactForm contactForm)
        {
            //sending an email 
            //step 1. add using system.net.mail
            //step 2. create a new message first
            MailMessage message = new MailMessage("theRobots@seedpaths.com", "mattfish490@gmail.com");
            //step 3. set subject
            message.Subject = "Contact request from";
            //step 4. construct the body with stringbuilder
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            sb.AppendLine("You have a new contact request.");
            sb.AppendLine("Name: " + contactForm.Name);
            sb.AppendLine("Email: " + contactForm.Email);
            sb.AppendLine("Message: " + contactForm.Message);
            sb.AppendLine(" I Love You");
            sb.AppendLine("- THe Robots");
            //step 5. Add Body to Message
            message.Body = sb.ToString();
            //step 6. Declare the SMTP client/aka the mail server
            SmtpClient client = new SmtpClient("mail.dustinkraft.com", 587);
            client.Credentials = new System.Net.NetworkCredential("postmaster@dustinkraft.com", "techIsFun1");
            //Step 7. Send message
            client.Send(message);
            return RedirectToAction("ThankYou", "Contact");
        }

        public ActionResult ThankYou()
        {
            return View();
        }

    }
}

Week6CodingChallenge/Week6CodingChallenge/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Week6CodingChallenge.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Week6CodingChallenge/Week6CodingChallenge/Controllers/WorkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Week6CodingChallenge.Controllers
{
    public class WorkController : Controller
    {
        //
        // GET: /Work/

        public ActionResult Index()
        {
            return PartialView();
        }

    }
}

Week6CodingChallenge/Week6CodingChallenge/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div id="siteContent">
<h2>Home</h2>
<div class="homeContainer">
    <div class="homeImg" align="center"><img src="~/Content/tw2.jpg" /></div>
    <div class="homeColum1">
        <h3>About</h3>
        <p>Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum.Lorem ipsum. Lorem ipsum.Lorem ipsum.Lorem ipsum.</p>
    </div>
    <div class="homeColum2">
        <h3>Work</h3>
         <p>Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum.Lorem ipsum. Lorem ipsum.Lorem ipsum.Lorem ipsum.</p>
    </div>
    <div class="homeColum3">
        <h3>Careers</h3>
         <p>Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum. Lorem ipsum.Lorem ipsum. Lorem ipsum.Lorem ipsum.Lorem ipsum.</p>
    </div>
</div>
</div>
<div id="tabcontent">

</div>

Week6CodingChallenge/Week6CodingChallenge/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <h1>Week 6 Coding Challenge</h1>
    &nbsp; &nbsp;
<div class="pageLink" id="page" data-url="@Url.Action("Index","Home")"><span><strong>Home</strong></span></div>
       &nbsp; &nbsp;
<div class="pageLink" id="tabs" data-url="@Url.Action("Index", "About")"><span><strong>About</strong></span></div>
    &nbsp; &nbsp;
<div class="pageLink" id="tabs" data-url="@Url.Action("Index", "Work")"><span><strong>Work</strong></span></div>
    &nbsp; &nbsp;
<div class="pageLink" id="tabs" data-url="@Url.Action("Index", "Contact")"><span><strong>Contact</strong></span></div>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    <script src="/scripts/main.js"></script>
    @RenderSection("scripts", required: false)
    
</body>
    <footer>
    <p> Copyright 2014 Matt Fisher &nbsp; &nbsp &nbsp; &nbsp &nbsp; &nbsp </p>
        <div class="footerNav">
        <a href="@Url.Action("Index", "About")">About Me</a> &nbsp; <a href="@Url.Action("Index", "Work")">Work</a> &nbsp; <a href="@Url.Action("Index", "Contact")">Contact</a>
        </div>
    </footer>
</html>